spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-template
    username: postgres
    password: postgres
  jwt:
    secret: ZG9sbGFyaGVhcmluZ3Bvc2l0aXZlbXVzY2xlbm9kZGVkY29va2llc2RlYWxjYXVnaHR0YXBlbGlzdGRpZmZlcmVuY2VtYWRyYW5tb3N0bHlyb3VuZGJlc2lkZWVuZ2luZXN0ZWVsbWVkaWNpbmVmYXZvcml0ZWRvbGxicmVlemU=